### ISSUE TITLE
Problems when using the API in my plugin

### ISSUE THREAD

**Issue by AILANTEL** [koca2000/NoteBlockAPI#101]
I tried to read your official documentation to use this API, but I always encounter a null pointer error when calling the methods. I checked my code repeatedly, making sure it is consistent with the usage in the official documentation, but the problem still persists. Spigot version 1.16.5, NoteBlockAPI version 1.6.1, server version 1.16.5, every time I call the playMusic0 method, I get a null pointer error. I have attached screenshots of my code and the error below. I put the loadMusic method in the onEnable method. I have also downloaded the NoteBlockAPI jar file and put it in the plugins folder of the server. I used the sout method to print out the Song object startSong and found that it was not null, startSong got the nbs file.
![{F27C4C0A-51E3-44b5-AE54-93E4572E9809}](https://github.com/koca2000/NoteBlockAPI/assets/95335008/d2c44557-39a5-4390-83f2-6a4ee5d2375a)

![{95C5B6BA-9D7F-46b9-A2D4-99142405EAD2}](https://github.com/koca2000/NoteBlockAPI/assets/95335008/494fe86a-3ffa-415d-a229-1938f3ef9d43)

**Comment by koca2000** [comment]
Hi! It looks like the NoteBlock API is not yet initialized at the time you call the `playMusic0` method. Have you added it as you plugin's dependency in plugin.yml? Is there any message about NoteBlockAPI in the server's startup log?

**Comment by AILANTEL** [comment]
I have written the dependencies in my plugin configuration file, and the server has successfully initialized the API.
![{57B641F1-3531-4afc-9FF9-23137C232003}](https://github.com/koca2000/NoteBlockAPI/assets/95335008/cf26070b-69dc-4122-8c56-94cd384f94cd)
![{0A73F5EA-660E-4916-AF9B-B806CBEA6B0A}](https://github.com/koca2000/NoteBlockAPI/assets/95335008/d4f59bde-124f-41c6-b6ec-3d7a139765d2)

**Comment by koca2000** [comment]
Assuming you are using maven, may I see your pom.xml file?

**Comment by AILANTEL** [comment]
I am using gradle, this is my build file, please take a look
![{47170490-4D90-4492-8DA1-E104F7A43155}](https://github.com/koca2000/NoteBlockAPI/assets/95335008/f424134a-2f34-40d7-8763-2051459c6cde)
![{0A7A1D0F-6113-4521-9536-831597791E0E}](https://github.com/koca2000/NoteBlockAPI/assets/95335008/798ac9ca-06c4-43ec-b199-8b465a6b77e0)

**Comment by koca2000** [comment]
I see. Please change the `implementation` to `compileOnly`. I'll update the wiki.

**Comment by AILANTEL** [comment]
“OK, I will try this method right away

**Comment by AILANTEL** [comment]
Thank you very much, the solution is very useful, my plugin can now play music normally!
