### ISSUE TITLE
Dependency 'com.github.koca2000:NoteBlockAPI:1.6.2' not found 

### ISSUE THREAD

**Issue by TazerGG** [koca2000/NoteBlockAPI#106]
It´s not finding the noteblockapi in jitpack.io

--------------------
<dependencies>
        <dependency>
            <groupId>com.github.koca2000</groupId>
            <artifactId>NoteBlockAPI</artifactId>
            <version>1.6.2</version>
        </dependency>
</dependencies>

**Comment by 42784** [comment]
Me too.[WARNING] Failed to download NoteBlockAPI-1.6.2.jar [https://jitpack.io/]

**Comment by koca2000** [comment]
Would you send me your pom file?

**Comment by 42784** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.axolotl</groupId>
    <artifactId>IdeaPlugin</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>IdeaPlugin</name>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.20.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.koca2000</groupId>
            <artifactId>NoteBlockAPI</artifactId>
            <version>1.6.2</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>

**Comment by koca2000** [comment]
Please try it again. For some unknown reason it seems like Jitpack.io lost the 1.6.2 jar file. I managed to force it to rebuild it and it should work fine now.

**Comment by 42784** [comment]
Okay, I can now obtain it normally, thank you! When I was using 1.6.1 for development, there was an issue with "the return value of" com. xxmicloxx. NoteBlockAPI. NoteBlockAPI. getAPI() "being null. Can I try 1.6.2 to see if it works
