### ISSUE TITLE
NoteBlockAPI.getAPI() is null

### ISSUE THREAD

**Issue by 42784** [koca2000/NoteBlockAPI#108]
Error reported during the use of paper 1.20.1:java.lang.NullPointerException: Cannot invoke "com.xxmicloxx.NoteBlockAPI.NoteBlockAPI.handleDeprecated(java.lang.StackTraceElement[])" because the return value of "com.xxmicloxx.NoteBlockAPI.NoteBlockAPI.getAPI()" is null

I can confirm that this API has loaded normally on the server (as can be seen through/plugins)

I used the jar obtained from Maven and the jar downloaded from Spigot to try com. xxmicloxx NoteBlockAPI. NoteBlockAPI. getAPI(), but both are null

By reading the source code of SongPlayer, I found this code: public SongPlayer (Song song, SoundCategory southern category) NoteBlockAPI. getAPI(). handleDepreciated (Thread. current Thread(). getStackTrace());

Because NoteBlockAPI. getAPI() is null, I encountered an error when using this plugin

I am not good at English. This was translated directly from Chinese through a translator, which may have some grammar errors and be difficult to understand. I am so sorry
![PixPin_2024-08-10_01-20-17](https://github.com/user-attachments/assets/326f9913-43b0-4bdc-9853-dc55a3d7d715)
![PixPin_2024-08-10_01-21-44](https://github.com/user-attachments/assets/bf73f3cd-47a6-4938-b540-b7e61c06af3b)

**Comment by koca2000** [comment]
Add `<scope>provided</scope>` to your pom inside the NoteBlockAPI dependency.

**Comment by 42784** [comment]
This is useful, I solved the problem and successfully played music on MC! thank!

**Comment by koca2000** [comment]
I am glad to hear that.
