### ISSUE TITLE
Stereo RadioSongPlayer

### ISSUE THREAD

**Issue by koca2000** [koca2000/NoteBlockAPI#17]
Play Note twice with offset to make it stereo.

**Comment by koca2000** [comment]
It will definitely be in CompatibilityUtil. But I am not sure that location based SongPlayers (NoteBlockSongPlayer and PositionSongPlayer) are also affected. Second question: what distance setting have you tried? I will make it constant (I am thinking about 0.5 or 1).

**Comment by SkytAsul** [comment]
I've only tried 2 and it works well...
