### ISSUE TITLE
Stereo playSound method

### ISSUE THREAD

**Issue by SkytAsul** [koca2000/NoteBlockAPI#18]
Hi,
Now you have changed the method **playSound** of _CompatibilityUtils_, previous plugins systems does not work anymore, cause of the new _boolean_ parameter.
Will you change that (by copying the last method without stereo paramter) or not ?

Thanks

**Comment by koca2000** [comment]
Hi,
I didn't expect that this method is used by other plugins directly. If it is needed I can add method without that parameter as well and mark it as deprecated.

**Comment by SkytAsul** [comment]
Yes, I've created my own SongPlayer (who extends Radio) to display particles on each tick with one note or more, so I'm using the CompatibilityUtils!

**Comment by koca2000** [comment]
You fully override playTick method? Why don't you call super method from that override?

**Comment by SkytAsul** [comment]
I don't want to compute again if there is notes on the tick played. By overriding all, I only have to create a boolean variable and if a note is played, the boolean is set to true. Then after all, it tests if there is note played and display a particle.

**Comment by koca2000** [comment]
I will add that mehod, but I would recommend you to use the super method. All you need is one small for cycle and if clause. I would like to warn you that I can make little internal change any time as I already did many times.

**Comment by SkytAsul** [comment]
OK, understood ! I hope that it will not produce too many lags
