### ISSUE TITLE
Problem with new version of NoteBlockStudio

### ISSUE THREAD

**Issue by SkytAsul** [koca2000/NoteBlockAPI#28]
I just created a song with the new version of NBS (3.4.0, available [here](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/releases)) and it seems that the file structure has changed (I'm getting "Song is corrupted" in console).
Will you add support to theses changes in NBAPI?

**Comment by koca2000** [comment]
I know about this change. I am the one who ask for it because of #26. The update is work in progress. It is not finished yet, but without custom instruments it should work. I'll release it as dev build.
