### ISSUE TITLE
Random SongPlayer loop replay the same song

### ISSUE THREAD

**Issue by SkytAsul** [koca2000/NoteBlockAPI#30]
Hey koca,
I'm (still) developing the playlist system of my plugin JukeBox, and I encountered a problem with the loop system. Here is my situation:
I have a SongPlayer with random mode enabled and repeat mode set to ALL. When the player arrives at the end of the song queue, a SongLoopEvent is called but instead of playing a random song from the playlist, it plays the same song again! I don't think this is the behavior you expected...
Could you please fix this?
Thanks!

PS: Sorry for taking all your time with my requests :/

**Comment by koca2000** [comment]
Hi!
I tried to find the bug, but it seems to be ok. I can't test it right now. Is it possible that you have only one song in playlist? Another option is that you have small amount of songs in playlist, so it randomly picks the same song.

Do you have songs in playlist before `SongLoopEvent` is fired?

**Comment by SkytAsul** [comment]
I'm currently using 5 short songs, and it always play the same music, and then it picks random songs.
Maybe I just got a very bad luck... I will retest.

**Comment by SkytAsul** [comment]
So it seems I've got a _very_ bad luck x) I have tested like 10 times... Nevermind, sorry for inconvenience.
