### ISSUE TITLE
NoteBlockStudio 3.5.0

### ISSUE THREAD

**Issue by SkytAsul** [koca2000/NoteBlockAPI#33]
Hey,
It seems that songs created with the latest version of OpenNoteBlockStudio (3.5.0) aren't working with NoteBlockAPI 1.4.1. Are you aware of this problem, and do you know how much time will it takes to be fixed?
Thanks!

**Comment by koca2000** [comment]
Hi!
I knew this problem will come, but I haven't noticed they already released it. It is not hard to fix, but I am on vacation. I'll see what I can do.

**Comment by SkytAsul** [comment]
Fixed with https://github.com/koca2000/NoteBlockAPI/commit/ec40ae3fc0397b86410d5a3e2e5b7ced74229bfd
