### ISSUE TITLE
API setPlayerVolume UUID

### ISSUE THREAD

**Issue by SkytAsul** [koca2000/NoteBlockAPI#34]
Hey,
Would it be possible to add this method in the class NoteBlockAPI:
```java
public static void setPlayerUUIDVolume(UUID id, byte volume) {
	plugin.playerVolume.put(id, volume);
}
```
Currently we can set the player's volume only when the player is online, and it's a bit annoying in some cases.
Thanks!

**Comment by koca2000** [comment]
I will add UUID variants for all NoteBlockAPI class methods.
