### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot add null to playlist

### ISSUE THREAD

**Issue by copyandexecute** [koca2000/NoteBlockAPI#40]
Yo dude what am I doing wrong?
Song song = NBSDecoder.parse(new File(Main.getPlugin().getDataFolder(), "wii.nbs"));
   Song song = NBSDecoder.parse(new File("/plugins/wii.nbs"));
   Song song = NBSDecoder.parse(new File("plugins/wii.nbs"));

it always says song is corrupted

**Comment by koca2000** [comment]
Hi! You are using version 1.4.4. Please download latest development build from [here](http://ci.haprosgames.com/job/NoteBlockAPI/).

**Comment by copyandexecute** [comment]
just wanted to let you know that its working
much love <3
