### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/xxmicloxx/NoteBlockAPI/utils/NBSDecoder

### ISSUE THREAD

**Issue by axobeast2020** [koca2000/NoteBlockAPI#42]
Yo dude what am I doing wrong?
My code in screen:
![Скриншот 05-04-2020 123531](https://user-images.githubusercontent.com/63187193/78471446-01c94e80-773a-11ea-869a-ed1290d837b5.png)

When i start my server and send the '/mm' command,  i get the next error in
1) server:
![Скриншот 05-04-2020 123708](https://user-images.githubusercontent.com/63187193/78471473-3937fb00-773a-11ea-8032-e32a304a12fa.png)
2) console:
![Скриншот 05-04-2020 123817](https://user-images.githubusercontent.com/63187193/78471495-5d93d780-773a-11ea-9be7-35057f831b78.png)

Do you help me please? Im really need to create this.

**Comment by koca2000** [comment]
Hi!

Do you have NoteBlockAPI .jar file in your plugins directory?

**Comment by axobeast2020** [comment]
Seriously? I don't know, that 'NoteBlockApi' should be in plugin`s directory! Ok, I'm trying it!

**Comment by axobeast2020** [comment]
Yesss! Its working! Thank you for help me!

**Comment by koca2000** [comment]
You are welcome!
