### ISSUE TITLE
[Feature request] Support sounds outside 2 octave range using resource pack

### ISSUE THREAD

**Issue by ishland** [koca2000/NoteBlockAPI#47]
Support these sounds outside 2 octave range using SongPlayer#setEnable10Octave(boolean)
If set to true, enable these sounds. 
If set to false, transpose these sounds.

**Comment by VoxPopuliZombiemold** [comment]
I would love to see support for this. I recently listened to a v4 note block studio track in full octave range via a data pack, and they sound great!!

NoteBlockAPI supporting this would god tier.
