### ISSUE TITLE
feat: add GitHub used by metric

### ISSUE THREAD

**Issue by T0biii** [koca2000/NoteBlockAPI#48]
GitHub introduced a "new" metric, which I find much more relevant than stars or downloads. It shows the number of times a dependency is used by other repositories.
Like: 
![Image of ](https://user-images.githubusercontent.com/103008/58381225-c4911d80-7fba-11e9-9179-1964cc18e963.png)
![Image of ](https://user-images.githubusercontent.com/103008/58381227-c9ee6800-7fba-11e9-907e-9c49e3cdeafa.png)

Copyed from https://github.com/netlify/staticgen/issues/ 507

you can see: https://github.com/T0biii/JoinMusic/network/dependencies is depending on it but it is not Linked to this GitHub Page

**Comment by koca2000** [comment]
It's a nice feature and I would like to enable it. However, I have no idea how to do it. Also I haven't found any Spigot project on Github that would have it. Maybe there is some incompatibility.

**Comment by T0biii** [comment]
mmmh https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API is a Java Project and got this 🤔

**Comment by koca2000** [comment]
I contacted the support and ask them how to do it. The API would have to be in maven central repository for it to work. However, I am not sure this really belongs to maven central repository so I won't upload it there, at least for now.
