### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by linusstretchtips** [koca2000/NoteBlockAPI#51]
Heya,

So im trying to use your API and i just want to make sure im doing this correct

Code
`public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if(sender instanceof Player){
            Player player = (Player) sender;

            Song song = NBSDecoder.parse(new File("path/to/file"));
            Song song2 = NBSDecoder.parse(new File("path/to/another/file"));

            Song song; 
            RadioSongPlayer rsp = new RadioSongPlayer(song);
            rsp.addPlayer(Player);
            rsp.setPlaying(true);

        }else{
            System.out.println("Sorry..But You cant execute this command in the console :(");
        }
        return true;
    }

Images:
![image](https://user-images.githubusercontent.com/64327566/83803948-4a06dd80-a6a5-11ea-9c43-7f0b5eceae95.png)
![image](https://user-images.githubusercontent.com/64327566/83803966-51c68200-a6a5-11ea-9482-ac4cf1ed5370.png)
![image](https://user-images.githubusercontent.com/64327566/83803996-5ee37100-a6a5-11ea-884a-5097f0280694.png)

Thanks

**Comment by linusstretchtips** [comment]
Add the Question Tag

**Comment by koca2000** [comment]
Why are you declaring `Song song` variable twice? You need to pass the variable that was created by `NBSDecoder` to the `RadioSongPlayer`.

**Comment by linusstretchtips** [comment]
im just following the wiki https://github.com/koca2000/NoteBlockAPI/wiki/Playing-songs

**Comment by linusstretchtips** [comment]
okay got this now
`            Song song = NBSDecoder.parse(new File("path/to/file"));
            Song song2 = NBSDecoder.parse(new File("path/to/another/file"));

             RadioSongPlayer rsp = new RadioSongPlayer(song);
            rsp.addPlayer((Player) sender);
            rsp.setPlaying(true);`

**Comment by linusstretchtips** [comment]
ag got it working

**Comment by linusstretchtips** [comment]
will inform you with anything else. Thanks fro the help

**Comment by koca2000** [comment]
The wiki assume that it's reader has basic knowledge of Java and it also is not 100% copy-paste. Feel free to ask if you need something.
