### ISSUE TITLE
Getting all song info

### ISSUE THREAD

**Issue by LewisTehMinerz** [koca2000/NoteBlockAPI#52]
I noticed that the following is ignored metadata:
https://github.com/koca2000/NoteBlockAPI/blob/da042cad7ab5294809a5d3cc916ede43e9ce8edb/src/main/java/com/xxmicloxx/NoteBlockAPI/NBSDecoder.java#L77
Is there any way I can get this metadata? I want to get the author of the original song as well as the author of the NBS file.

**Comment by koca2000** [comment]
Hi! I'll store this value in Song class in next version.
