### ISSUE TITLE
How to play a scale of 2 octaves or more

### ISSUE THREAD

**Issue by Re1ga** [koca2000/NoteBlockAPI#69]
I'm trying to play a scale of 2 octaves or more, but even if I use the resource pack, the sound doesn't sound.
(Most of the songs I converted from midi seemed to have to use resource packs.)

How can I make a sound?
Do I need to write anything special on the plugin side?

**Comment by koca2000** [comment]
Hi @Re1ga! The default behaviour is that all notes are transposed to 2 octaves Minecraft is able to play on it's own. So you should hear your song even without resource pack or any other settings. To disable transposing mechanism and play the song in extended octave range use `SongPlayer.setEnable10Octave(true);`.

**Comment by Re1ga** [comment]
thanks so much @koca2000!!!
