### ISSUE TITLE
No New update available!

### ISSUE THREAD

**Issue by ErythroCraft** [koca2000/NoteBlockAPI#76]
Hi.

I'm using the latest available version of the NoteBlockAPI (NoteBlockAPI-1.6.1-SNAPSHOT)
 with JukeBox on a 1.16.5 spigot server.

The server installed the NoteBlockAPI, but on loading the server console say 
**[08:18:00] [Craft Scheduler Thread - 7/INFO]: [NoteBlockAPI] New update available!**

Where I can download the newest version?

**Comment by koca2000** [comment]
Hi! I am sorry for that. I accidentally uploaded SNAPSHOT jar instead of release jar to Spigot so the updater thinks there is newer release. If you want to get rid of this message you can download development build [here](http://ci.haprosgames.com/job/NoteBlockAPI/).

**Comment by nathanfranke** [comment]
@koca2000 While the CI server is down, can you upload a copy of the plugin somewhere else?

**Comment by koca2000** [comment]
@nathanfranke It is on my [Discord](https://discord.gg/TeUBgb5) and the CI server is going to be back online in few days.
