### ISSUE TITLE
Plugin not properly shutting down

### ISSUE THREAD

**Issue by srnyx** [koca2000/NoteBlockAPI#80]
Happens when I stop/restart my server (it's spammed like 100 times): https://paste.srnyx.xyz/fusucolewu.md

**Comment by koca2000** [comment]
Hi! I am sorry for late reply. I must have missed it. Would you please give me some more information about your server? When NoteBlockAPI's onDisable method is called it sets a flag for all SongPlayer's that they should end themself which happens after it's thread wakes up. It looks like your server doesn't like to wait a few milisecond.

**Comment by srnyx** [comment]
> Hi! I am sorry for late reply. I must have missed it. Would you please give me some more information about your server? When NoteBlockAPI's onDisable method is called it sets a flag for all SongPlayer's that they should end themself which happens after it's thread wakes up. It looks like your server doesn't like to wait a few milisecond.

Purpur 1.117.1
Music plugin: https://www.spigotmc.org/resources/advancednbs.81195/

**Comment by koca2000** [comment]
I pushed a commit with the fix. I was already cancelling all Bukkit scheduler tasks but according to CraftBukkit source code it doesn't interrupt running threads.
