### ISSUE TITLE
entity playback seems to "round the location"?

### ISSUE THREAD

**Issue by Speeder323** [koca2000/NoteBlockAPI#84]
At least when played with Denizen(+ Depenizen), NoteblockAPI seems to snap the source of the playsound to the block corner.
(Version: 1.6.1-SNAPSHOT, Could not check the dev builds due to website timing out.)

**Comment by koca2000** [comment]
Hi! There is no rounding in NoteBlockAPI's code. Entity location is used (`entity.getLocation()`).

**Comment by koca2000** [comment]
Since there is no rounding in the NoteBlockAPI it seems that there is no issue on my side that I can fix. If any new information appear that would indicate a bug in NoteBlockAPI I will reopen the issue.
