### ISSUE TITLE
jenkins dev builds are down / 1.18.2 support?

### ISSUE THREAD

**Issue by mrfloris** [koca2000/NoteBlockAPI#86]
Hey there, sorry to report this via github, i am not sure where else to throw this.

Jenkins server appears to be unreachable. I was trying to check for 1.18.2 support.

**Comment by koca2000** [comment]
The latest release of NoteBlockAPI is compatible with Spigot 1.18.2. I am working on getting Jenkins back online.

**Comment by mrfloris** [comment]
> The latest release of NoteBlockAPI is compatible with Spigot 1.18.2. I am working on getting Jenkins back online.

Awesome, thank you; have a lovely weekend.
