### ISSUE TITLE
what is the maven version number

### ISSUE THREAD

**Issue by Torben0612** [koca2000/NoteBlockAPI#88]
what is the maven version number for using the noteblockapi

here is my pom.xml file https://gist.github.com/Torben0612/0fc348d960baa8de670da5fecfbc8585

**Comment by koca2000** [comment]
Hi! The `-SNAPSHOT` version you have in your pom always points to the last commit in the master branch in this repository. Your IDE may mark is as an error because it is not specified in the manifest but when you try to build it with maven it will work.

**Comment by Torben0612** [comment]
ok thanks :)
