### ISSUE TITLE
Song is corrupted

### ISSUE THREAD

**Issue by xHyroM** [koca2000/NoteBlockAPI#90]
NoteBlockAPI keeps telling me that the song is corrupted but in NoteBlock Studio it works perfectly.
Version:  v1.6.1

Songs:
- https://github.com/thatcraniumguy/Songs/blob/master/NBS%20files/A%20Nightmare%20Before%20Christmas.nbs
- https://github.com/thatcraniumguy/Songs/blob/master/NBS%20files/Wizards%20in%20Winter.nbs

**Comment by koca2000** [comment]
Hi!

I tried to reproduce the error. However, the songs were loaded with NoteBlockAPI 1.6.1 and played using NoteBlockMusicPlayer 1.9.0-SNAPSHOT without any problem. What plugin do you use NoteBlockAPI with?

**Comment by koca2000** [comment]
I am closing this for now. If the issue appears again or you have some some information, I can reopen it.
